import { Bike, GetBikeResponse } from "types";

export const BikesEmptyMock = <GetBikeResponse>{
  bikes: [],
};

export const BikeMock = <Bike>{
  date_stolen: 1677733200,
  description: "",
  frame_colors: ["Silver, gray or bare metal"],
  frame_model: "Cube Nuride Hybrid Performance Allroad",
  id: 1466472,
  is_stock_img: false,
  large_img: null,
  location_found: null,
  manufacturer_name: "Cube",
  external_id: null,
  registry_name: null,
  registry_url: null,
  serial: "Wow65261kgat",
  status: "stolen",
  stolen: true,
  stolen_coordinates: [48.18, 11.52],
  stolen_location: "Munich, 80992, DE",
  thumb: null,
  title: "2022 Cube Cube Nuride Hybrid Performance Allroad",
  url: "https://bikeindex.org/bikes/1466472",
  year: 2022,
};

export const BikesMock = <GetBikeResponse>{
  bikes: [
    {
      date_stolen: 1677733200,
      description: "",
      frame_colors: ["Silver, gray or bare metal"],
      frame_model: "Cube Nuride Hybrid Performance Allroad",
      id: 1466472,
      is_stock_img: false,
      large_img: null,
      location_found: null,
      manufacturer_name: "Cube",
      external_id: null,
      registry_name: null,
      registry_url: null,
      serial: "Wow65261kgat",
      status: "stolen",
      stolen: true,
      stolen_coordinates: [48.18, 11.52],
      stolen_location: "Munich, 80992, DE",
      thumb: null,
      title: "2022 Cube Cube Nuride Hybrid Performance Allroad",
      url: "https://bikeindex.org/bikes/1466472",
      year: 2022,
    },
    {
      date_stolen: 1670774400,
      description: null,
      frame_colors: ["Black"],
      frame_model: "Reaction Hybrid One 625",
      id: 1447938,
      is_stock_img: false,
      large_img:
        "https://files.bikeindex.org/uploads/Pu/663811/large_82B71593-C4EF-470D-AEF5-5310D889E0CB.jpeg",
      location_found: null,
      manufacturer_name: "Cube",
      external_id: null,
      registry_name: null,
      registry_url: null,
      serial: "WOW62005PVNT",
      status: "stolen",
      stolen: true,
      stolen_coordinates: [48.16, 11.54],
      stolen_location: "München, 80637, DE",
      thumb:
        "https://files.bikeindex.org/uploads/Pu/663811/small_82B71593-C4EF-470D-AEF5-5310D889E0CB.jpeg",
      title: "2022 Cube Reaction Hybrid One 625",
      url: "https://bikeindex.org/bikes/1447938",
      year: 2022,
    },
    {
      date_stolen: 1657602000,
      description: "",
      frame_colors: ["Silver, gray or bare metal", "Black"],
      frame_model: "Nuride Hybrid Performance 625 Allroad",
      id: 1342891,
      is_stock_img: false,
      large_img:
        "https://files.bikeindex.org/uploads/Pu/605297/large_IMG-20220602-WA0000.jpeg",
      location_found: null,
      manufacturer_name: "Cube",
      external_id: null,
      registry_name: null,
      registry_url: null,
      serial: "Unknown",
      status: "stolen",
      stolen: true,
      stolen_coordinates: [48.1, 11.53],
      stolen_location: "München, 81379, DE",
      thumb:
        "https://files.bikeindex.org/uploads/Pu/605297/small_IMG-20220602-WA0000.jpeg",
      title: "2022 Cube Nuride Hybrid Performance 625 Allroad",
      url: "https://bikeindex.org/bikes/1342891",
      year: 2022,
    },
    {
      date_stolen: 1654038000,
      description: "new eBike",
      frame_colors: ["Silver, gray or bare metal"],
      frame_model: "Trapez 28 : 50 cm",
      id: 1310219,
      is_stock_img: false,
      large_img:
        "https://files.bikeindex.org/uploads/Pu/579271/large_IMG_20220601_019.JPG",
      location_found: null,
      manufacturer_name: "Kreitler",
      external_id: null,
      registry_name: null,
      registry_url: null,
      serial: "PDEJM14107",
      status: "stolen",
      stolen: true,
      stolen_coordinates: [48.11, 11.69],
      stolen_location: "Munich, 81827, DE",
      thumb:
        "https://files.bikeindex.org/uploads/Pu/579271/small_IMG_20220601_019.JPG",
      title: "2022 Kreitler Trapez 28 : 50 cm",
      url: "https://bikeindex.org/bikes/1310219",
      year: 2022,
    },
    {
      date_stolen: 1654038000,
      description: "",
      frame_colors: ["Silver, gray or bare metal"],
      frame_model: "Wave",
      id: 1310249,
      is_stock_img: false,
      large_img:
        "https://files.bikeindex.org/uploads/Pu/579285/large_IMG_20220601_020.JPG",
      location_found: null,
      manufacturer_name: "Kreitler",
      external_id: null,
      registry_name: null,
      registry_url: null,
      serial: "PDEJM14146",
      status: "stolen",
      stolen: true,
      stolen_coordinates: [48.11, 11.69],
      stolen_location: "Munich, 81827, DE",
      thumb:
        "https://files.bikeindex.org/uploads/Pu/579285/small_IMG_20220601_020.JPG",
      title: "2022 Kreitler Wave",
      url: "https://bikeindex.org/bikes/1310249",
      year: 2022,
    },
    {
      date_stolen: 1653512400,
      description:
        "Es hat einen Stadler Aufkleber und in sehr gutem Zustand. Es hat zwei Schutzbleche und eventuell eine Halterung für ein GPS Gerät am Lenker",
      frame_colors: ["Black", "Blue"],
      frame_model: "Racer street",
      id: 1305286,
      is_stock_img: false,
      large_img:
        "https://files.bikeindex.org/uploads/Pu/574070/large_IMG_20220528_123304.jpg",
      location_found: null,
      manufacturer_name: "BULLS Bikes",
      external_id: null,
      registry_name: null,
      registry_url: null,
      serial: "Unknown",
      status: "stolen",
      stolen: true,
      stolen_coordinates: [48.11, 11.61],
      stolen_location: "Munich, 81669, DE",
      thumb:
        "https://files.bikeindex.org/uploads/Pu/574070/small_IMG_20220528_123304.jpg",
      title: "BULLS Bikes Racer street",
      url: "https://bikeindex.org/bikes/1305286",
      year: null,
    },
    {
      date_stolen: 1649192400,
      description: null,
      frame_colors: ["White", "Black"],
      frame_model: "GHQ255803",
      id: 1261935,
      is_stock_img: false,
      large_img: null,
      location_found: null,
      manufacturer_name: "Ghost",
      external_id: null,
      registry_name: null,
      registry_url: null,
      serial: "WRC10775078",
      status: "stolen",
      stolen: true,
      stolen_coordinates: [48.14, 11.69],
      stolen_location: "München, 81829, DE",
      thumb: null,
      title: "2015 Ghost GHQ255803",
      url: "https://bikeindex.org/bikes/1261935",
      year: 2015,
    },
    {
      date_stolen: 1636315575,
      description: null,
      frame_colors: ["Red"],
      frame_model: "Mini Max Wifi",
      id: 1185322,
      is_stock_img: false,
      large_img:
        "https://files.bikeindex.org/uploads/Pu/496276/large_46F969D7-2E72-4B3B-907C-A44D92315C50.jpeg",
      location_found: null,
      manufacturer_name: "Omnium",
      external_id: null,
      registry_name: null,
      registry_url: null,
      serial: "JVM8462P",
      status: "stolen",
      stolen: true,
      stolen_coordinates: [48.12, 11.6],
      stolen_location: "München, 81669, DE",
      thumb:
        "https://files.bikeindex.org/uploads/Pu/496276/small_46F969D7-2E72-4B3B-907C-A44D92315C50.jpeg",
      title: "2021 Omnium Mini Max Wifi cargo bike (front storage)",
      url: "https://bikeindex.org/bikes/1185322",
      year: 2021,
    },
    {
      date_stolen: 1633525200,
      description: null,
      frame_colors: ["Black", "Red"],
      frame_model: "Hybrid 140 Pro",
      id: 1171384,
      is_stock_img: false,
      large_img: null,
      location_found: null,
      manufacturer_name: "Cube",
      external_id: null,
      registry_name: null,
      registry_url: null,
      serial: "WOW00401LM0315P",
      status: "stolen",
      stolen: true,
      stolen_coordinates: [48.15, 11.53],
      stolen_location: "München, 80634, DE",
      thumb: null,
      title: "2016 Cube Hybrid 140 Pro",
      url: "https://bikeindex.org/bikes/1171384",
      year: 2016,
    },
    {
      date_stolen: 1631016000,
      description: null,
      frame_colors: ["Red"],
      frame_model: "XD3",
      id: 1151412,
      is_stock_img: false,
      large_img:
        "https://files.bikeindex.org/uploads/Pu/479382/large_IMG_3160.JPG",
      location_found: null,
      manufacturer_name: "HNF Nicolai Germany",
      external_id: null,
      registry_name: null,
      registry_url: null,
      serial: "WEUHN2BXKCX01439",
      status: "stolen",
      stolen: true,
      stolen_coordinates: [48.02, 11.57],
      stolen_location: "Oberhaching, 82041, DE",
      thumb: "https://files.bikeindex.org/uploads/Pu/479382/small_IMG_3160.JPG",
      title: "2020 HNF Nicolai Germany XD3",
      url: "https://bikeindex.org/bikes/1151412",
      year: 2020,
    },
  ],
};
